### ISSUE TITLE
 Failed precondition: Attempting to use uninitialized value yolo_layer/Variable

### ISSUE THREAD

**Issue by kankratekaran** [experiencor/keras-yolo3#208]
I am getting following error while running the train.py script on raccoon dataset. Please guide to what can I do here.

2019-08-07 13:28:42.442882: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "train.py", line 280, in <module>
    _main_(args)
  File "train.py", line 257, in _main_
    max_queue_size   = 8
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training_generator.py", line 264, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1175, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Attempting to use uninitialized value yolo_layer/Variable
	 [[{{node yolo_layer/AssignAdd}}]]
	 [[yolo_layer_2/add_16/_3303]]
  (1) Failed precondition: Attempting to use uninitialized value yolo_layer/Variable
	 [[{{node yolo_layer/AssignAdd}}]]
0 successful operations.
0 derived errors ignored.

**Comment by kankratekaran** [comment]
Problem solved. There is nothing to do with code. It is more of a kind a memory error. Adding the following to the top of train.py code helped me.

config = tf.ConfigProto()
config.gpu_options.allow_growth = True
tf.keras.backend.set_session(tf.Session(config=config))

 See [link](https://github.com/tensorflow/tensorflow/issues/24496) for more info.
